### ISSUE TITLE
Lost file

### ISSUE THREAD

**Issue by GingerTaleFX** [agavrel/42-fractol#1]
you lost ft_color_converter.c and your project doesn't work
and u should write, that project is for linux.

**Comment by pulgamecanica** [comment]
Hello, I stumbled across this repo and I fixed it for you :D

check out my fork where you can finally compile it, I also recreated this missing file
[fork :fork_and_knife: ](https://github.com/pulgamecanica/42-fractol)

I did this project some time ago so it was not very hard to make it work...

Result:

https://github.com/agavrel/42-fractol/assets/28810331/a806550f-4b90-4706-b28a-5b2b67eefece

**Comment by agavrel** [comment]
Hi @pulgamecanica  , Thank you so much, I have merged your PR, Cheers,
